name: '[FULL] ubuntu-18.04.'

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        
      - name: Update apt repos
        run: sudo apt-get update
        
      - name: Install Bitcoin PPA 
        run: sudo apt-get install libsecp256k1-0 python3-pyqt5 automake libtool python3-cryptography python3-setuptools python3-pip
        
      - name: autogen 
        run: ./contrib/make_libsecp256k1.sh
        
      - name: autogen 
        run: python3 -m pip install --user .
